# Imagen base de Node
FROM node:18

# Crear directorio dentro del contenedor
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install -g expo-cli && npm install

# Copiar el resto del proyecto
COPY . .

# Exponer puertos de Expo (Metro bundler y dev tools)
EXPOSE 19000 19001 19002

# Comando por defecto
CMD ["npx", "expo", "start", "--tunnel"]
